// Hand-Lexikon für Chinese Classical (Millington). Datenbasis für den
// Lexikon-Bildschirm, die Entwicklungshinweise und die Übungshände.
//
// Felder:
//   id        stabile Kennung (bei Scoring-Zeilen identisch mit SCORE_RULES)
//   category  'basics' | 'points' | 'double' | 'limit' | 'option'
//   rule      ID in SCORE_RULES (Wert und Labels), optional
//   name      { de, en }
//   text      { de } Erklärung
//   example   Kurznotation einer Beispielhand (14 Steine) oder null
//   tip       { de } Aufbautipp
//   rarity    1 (häufig) .. 5 (sehr selten)
//   standard  true = Millington-Standard, false = Option
//   form      Zielform für die Analyse (siehe analysis/forms.js), optional

export const LEXICON = [
  // --- Grundlagen ---
  {
    id: 'basics_sets', category: 'basics', name: { de: 'Sätze und Paar', en: 'Sets and pair' },
    text: { de: 'Eine fertige Standardhand besteht aus vier Sätzen und einem Paar (14 Steine). Sätze sind Chow (drei aufeinanderfolgende Steine einer Farbe), Pung (drei gleiche) und Kong (vier gleiche). Chows sind punktlos, Pungs und Kongs bringen Grundpunkte, verdeckt doppelt so viele wie offen.', en: 'A complete standard hand has four sets and a pair (14 tiles). Sets are chow (three consecutive tiles of one suit), pung (three identical) and kong (four identical). Chows score nothing; pungs and kongs score base points, concealed twice as much as exposed.' },
    example: '123b 456c 789k EEE rr', tip: { de: 'Behalte Paare und Pungs aus Honours: sie bringen Punkte und Verdopplungen. Chows sind schnell, aber wertlos.', en: 'Keep pairs and pungs of honours: they bring points and doubles. Chows are fast but worthless.' }, rarity: 1, standard: true,
  },
  {
    id: 'basics_calls', category: 'basics', name: { de: 'Rufen: Chow, Pung, Kong, Mahjong', en: 'Calls' },
    text: { de: 'Ein Abwurf kann gerufen werden: Chow nur vom linken Nachbarn (Vorspieler), Pung und Kong von jedem, Mahjong von jedem. Vorrang: Mahjong vor Pung/Kong vor Chow; bei mehreren Mahjong-Rufen gewinnt der nächste in Spielreihenfolge. Gerufene Sätze liegen offen und zählen weniger; die Hand verliert die Verdopplung für die verdeckte Hand.', en: 'A discard can be claimed: chow only from the left neighbour (the player before you), pung and kong from anyone, Mahjong from anyone. Priority: Mahjong before pung/kong before chow; with several Mahjong claims the next player in turn order wins. Claimed sets are exposed and score less; the hand loses the concealed-hand double.' },
    example: null, tip: { de: 'Rufe nur, wenn die Hand dadurch einen Schritt näher ans Warten rückt. Ein früher Chow verrät deine Farbe und öffnet die Hand.', en: 'Only call when the hand gets one step closer to ready. An early chow reveals your suit and opens the hand.' }, rarity: 1, standard: true,
  },
  {
    id: 'basics_scoring', category: 'basics', name: { de: 'Punkte, Verdopplungen, Limit', en: 'Points, doubles, limit' },
    text: { de: 'Jeder Spieler zählt seine Hand: Grundpunkte (Mahjong 20, Sätze, Paare, Bonussteine, Gewinnart) mal 2 je Verdopplung, gekappt auf das Limit (500, Option 1000). Limit-Hände zählen genau das Limit. Der Gewinner erhält seinen Wert von allen drei anderen; die Verlierer begleichen untereinander die Differenz ihrer Handwerte. Ost zahlt und erhält doppelt.', en: 'Every player counts their hand: base points (Mahjong 20, sets, pairs, bonus tiles, way of winning) times 2 per double, capped at the limit (500, option 1000). Limit hands score exactly the limit. The winner receives their value from each of the other three; the losers settle the difference of their hand values among themselves. East pays and receives double.' },
    example: null, tip: { de: 'Auch als Verlierer zählen Pungs, Paare aus Drachen und Winden und Bonussteine. Eine wertlose Hand kostet doppelt: gegen den Gewinner und gegen die anderen Verlierer.', en: 'Even as a loser, pungs, pairs of dragons and winds and bonus tiles count. A worthless hand costs twice: against the winner and against the other losers.' }, rarity: 1, standard: true,
  },
  {
    id: 'basics_east', category: 'basics', name: { de: 'Ost, Winde und Runden', en: 'East, winds and rounds' },
    text: { de: 'Ost ist Geber, beginnt mit 14 Steinen, zahlt und erhält doppelt. Gewinnt Ost oder endet die Hand unentschieden, bleibt Ost; sonst wandert der Geber weiter. Nach vier Gebern wechselt der Rundenwind (Ost, Süd, West, Nord). Pung und Paar des eigenen Windes und des Rundenwindes bringen Verdopplung bzw. Punkte.', en: 'East is the dealer, starts with 14 tiles, pays and receives double. If East wins or the hand is drawn, East stays; otherwise the deal moves on. After four dealers the prevailing wind changes (East, South, West, North). Pung and pair of your own wind and of the prevailing wind bring a double or points.' },
    example: null, tip: { de: 'Als Ost lohnt sich Tempo: jede Hand zählt doppelt, gewonnen wie verloren.', en: 'As East, tempo pays: every hand counts double, won or lost.' }, rarity: 1, standard: true,
  },
  {
    id: 'basics_wall', category: 'basics', name: { de: 'Wand, Kong-Box, Unentschieden', en: 'Wall, kong box, draw' },
    text: { de: 'Die lebende Wand liefert die Züge; die Kong-Box (tote Wand, 14 Steine) liefert Ersatzsteine nach Kongs und Bonussteinen und wird nach Millington aus der lebenden Wand aufgefüllt. Ist die lebende Wand leer, endet die Hand unentschieden ohne Punkte, Ost bleibt.', en: 'The live wall supplies the draws; the kong box (dead wall, 14 tiles) supplies replacement tiles after kongs and bonus tiles and is refilled from the live wall after Millington. When the live wall is empty the hand is drawn without points and East stays.' },
    example: null, tip: { de: 'Spät im Spiel gilt: kein Stein ist mehr sicher, den ein Gegner mit offenen Sätzen brauchen könnte. Wirf Steine, die bereits dreimal sichtbar sind.', en: 'Late in the hand no tile is safe any more that an opponent with exposed sets could need. Discard tiles that are already visible three times.' }, rarity: 1, standard: true,
  },

  // --- Punkte (Auswahl, Rest aus SCORE_RULES) ---
  { id: 'pung_major_closed', category: 'points', rule: 'pung_major_closed', name: { de: 'Verdeckter Pung Endsteine/Honours', en: 'Concealed pung of terminals/honours' }, text: { de: 'Drei gleiche 1er, 9er, Winde oder Drachen, selbst gezogen (nicht gerufen): 8 Punkte. Offen 4, einfache Steine 4 verdeckt / 2 offen.', en: 'Three identical 1s, 9s, winds or dragons, drawn yourself (not claimed): 8 points. Exposed 4; simples 4 concealed / 2 exposed.' }, example: '111b 456c 789k EEE rr', tip: { de: 'Ein Paar Endsteine oder Honours früh behalten: die dritte Kopie macht daraus den wertvollsten Pung.', en: 'Keep a pair of terminals or honours early: the third copy makes the most valuable pung.' }, rarity: 1, standard: true },
  { id: 'kong_major_closed', category: 'points', rule: 'kong_major_closed', name: { de: 'Verdeckter Kong', en: 'Concealed kong' }, text: { de: 'Vier gleiche Steine aus der Hand angesagt: 32 Punkte für Endsteine/Honours, 16 für einfache. Nach einem Kong ziehst du einen Ersatzstein aus der Kong-Box.', en: 'Four identical tiles declared from the hand: 32 points for terminals/honours, 16 for simples. After a kong you draw a replacement tile from the kong box.' }, example: null, tip: { de: 'Ein Kong bringt einen Extra-Zug und Punkte, verrät aber deine Sammlung. Vier Kongs sind ein Limit.', en: 'A kong brings an extra draw and points but reveals what you collect. Four kongs are a limit.' }, rarity: 2, standard: true },
  { id: 'pair_dragon', category: 'points', rule: 'pair_dragon', name: { de: 'Paar Drachen / Winde', en: 'Pair of dragons or winds' }, text: { de: 'Ein Paar aus Drachen, dem eigenen Wind oder dem Rundenwind bringt 2 Punkte (eigener Wind als Rundenwind: 4).', en: 'A pair of dragons, your own wind or the prevailing wind brings 2 points (own wind that is also prevailing: 4).' }, example: null, tip: { de: 'Ideal als Paar der fertigen Hand.', en: 'Ideal as the pair of the finished hand.' }, rarity: 1, standard: true },
  { id: 'win_only_possible', category: 'points', rule: 'win_only_possible', name: { de: 'Warten auf einen einzigen Stein', en: 'Waiting on the only possible tile' }, text: { de: 'Kantenwarten (12 → 3), Mittelwarten (13 → 2) oder Paarwarten bringen 2 Punkte, wenn kein anderer Stein die Hand vervollständigt hätte.', en: 'Edge wait (12 → 3), closed wait (13 → 2) or pair wait bring 2 points if no other tile would have completed the hand.' }, example: '123b 456c 789k EEE 55k', tip: { de: 'Ein breites Warten (mehr Steine) ist trotzdem meist besser als 2 Punkte.', en: 'A wide wait (more tiles) is usually still better than 2 points.' }, rarity: 1, standard: true },
  { id: 'win_self_draw', category: 'points', rule: 'win_self_draw', name: { de: 'Selbstzug', en: 'Self-draw' }, text: { de: 'Gewinn mit einem selbst gezogenen Stein: 2 Punkte; alle drei Gegner zahlen. Mit letztem Wandstein, Kong-Ersatzstein oder Kong-Raub je 2 weitere.', en: 'Winning with a self-drawn tile: 2 points; all three opponents pay. With the last wall tile, a kong replacement tile or by robbing a kong 2 more each.' }, example: null, tip: { de: 'Verdeckte Hand plus Selbstzug ergibt die Verdopplung "verdeckte Hand".', en: 'Concealed hand plus self-draw yields the concealed-hand double.' }, rarity: 1, standard: true },

  // --- Verdopplungen ---
  { id: 'dbl_pung_dragon', category: 'double', rule: 'dbl_pung_dragon', name: { de: 'Drachen-Pung', en: 'Dragon pung' }, text: { de: 'Jeder Pung oder Kong aus Roten, Grünen oder Weißen Drachen verdoppelt die Hand, auch für Verlierer.', en: 'Every pung or kong of red, green or white dragons doubles the hand, also for losers.' }, example: '123b 456c 789k rrr EE', tip: { de: 'Der einfachste Weg zu Verdopplungen: zwei Drachen behalten, die dritte kommt oft per Ruf.', en: 'The simplest route to doubles: keep two dragons, the third often comes by call.' }, rarity: 1, standard: true, form: 'standard' },
  { id: 'dbl_pung_own_wind', category: 'double', rule: 'dbl_pung_own_wind', name: { de: 'Pung des eigenen Windes / Rundenwindes', en: 'Own wind / prevailing wind pung' }, text: { de: 'Pung oder Kong deines Sitzwindes: 1 Verdopplung; des Rundenwindes: 1 weitere. Als Ost in der Ostrunde sind das 2 Verdopplungen für einen Ost-Pung.', en: 'Pung or kong of your seat wind: 1 double; of the prevailing wind: 1 more. As East in the East round an East pung is worth 2 doubles.' }, example: '123b 456c 789k EEE 55k', tip: { de: 'Fremde Winde sind wertlos für dich: früh abwerfen, bevor sie gefährlich werden.', en: 'Foreign winds are worthless to you: discard them early before they become dangerous.' }, rarity: 1, standard: true, form: 'standard' },
  { id: 'dbl_no_chow', category: 'double', rule: 'dbl_no_chow', name: { de: 'Nur Pungs (All Pungs)', en: 'All pungs' }, text: { de: 'Vier Pungs/Kongs und ein Paar, kein Chow: 1 Verdopplung, dazu die Grundpunkte aller Pungs. Verdeckt und per Selbstzug gewonnen wird daraus der Verborgene Schatz (Limit).', en: 'Four pungs/kongs and a pair, no chow: 1 double plus the base points of all pungs. Won concealed by self-draw it becomes Buried Treasure (limit).' }, example: '111b 555c 999k EEE rr', tip: { de: 'Sammle Paare statt Reihen; rufe Pungs, wenn die Hand sonst zu langsam wird.', en: 'Collect pairs instead of runs; claim pungs when the hand would otherwise be too slow.' }, rarity: 2, standard: true, form: 'all_pungs' },
  { id: 'dbl_concealed', category: 'double', rule: 'dbl_concealed', name: { de: 'Verdeckte Hand', en: 'Concealed hand' }, text: { de: 'Kein gerufener Satz (verdeckte Kongs erlaubt) und Gewinn per Selbstzug: 1 Verdopplung. Alle Pungs zählen dann als verdeckt.', en: 'No claimed set (concealed kongs allowed) and winning by self-draw: 1 double. All pungs then count as concealed.' }, example: null, tip: { de: 'Lohnt sich vor allem mit Pung-Händen: verdeckte Pungs zählen doppelt und die Hand wird verdoppelt.', en: 'Worth most with pung hands: concealed pungs count double and the hand is doubled.' }, rarity: 2, standard: true, form: 'concealed' },
  { id: 'dbl_three_concealed_pungs', category: 'double', rule: 'dbl_three_concealed_pungs', name: { de: 'Drei verdeckte Pungs', en: 'Three concealed pungs' }, text: { de: 'Drei selbst gezogene Pungs in der Hand: 1 Verdopplung, unabhängig vom vierten Satz.', en: 'Three self-drawn pungs in the hand: 1 double, regardless of the fourth set.' }, example: null, tip: { de: 'Der Weg zum Verborgenen Schatz: vier verdeckte Pungs und Selbstzug.', en: 'The road to Buried Treasure: four concealed pungs and self-draw.' }, rarity: 3, standard: true, form: 'all_pungs' },
  { id: 'dbl_half_flush', category: 'double', rule: 'dbl_half_flush', name: { de: 'Eine Farbe mit Honours (Half Flush)', en: 'Half flush' }, text: { de: 'Alle Steine aus einer Farbe plus Winde/Drachen: 1 Verdopplung. Häufig kombiniert mit Drachen- oder Wind-Pungs.', en: 'All tiles from one suit plus winds/dragons: 1 double. Often combined with dragon or wind pungs.' }, example: '123b 456b 999b EEE rr', tip: { de: 'Wenn eine Farbe schon 6 bis 7 Steine stellt, lohnt der Umbau. Honours-Paare passen dazu.', en: 'If one suit already supplies 6 to 7 tiles, the conversion pays. Honour pairs fit in.' }, rarity: 2, standard: true, form: 'half_flush' },
  { id: 'dbl_full_flush', category: 'double', rule: 'dbl_full_flush', name: { de: 'Reine Farbe (Full Flush)', en: 'Full flush' }, text: { de: 'Alle 14 Steine aus einer Farbe: 3 Verdopplungen. Vollständig verdeckt ist die reine Farbe ein Limit.', en: 'All 14 tiles from one suit: 3 doubles. Fully concealed, the full flush is a limit.' }, example: '123b 456b 789b 234b 99b', tip: { de: 'Braucht Zeit und verrät sich: Gegner werfen deine Farbe nicht mehr. Chow-Rufe vom linken Nachbarn helfen.', en: 'Takes time and gives itself away: opponents stop discarding your suit. Chow calls from the left neighbour help.' }, rarity: 3, standard: true, form: 'full_flush' },
  { id: 'dbl_terminals_honours', category: 'double', rule: 'dbl_terminals_honours', name: { de: 'Nur Endsteine und Honours', en: 'All terminals and honours' }, text: { de: 'Alle Sätze und das Paar bestehen aus 1ern, 9ern, Winden und Drachen: 1 Verdopplung plus hohe Grundpunkte (alle Pungs sind Major).', en: 'All sets and the pair consist of 1s, 9s, winds and dragons: 1 double plus high base points (all pungs are major).' }, example: '111b 999c EEE rrr 99k', tip: { de: 'Ohne Chows: nur Pungs möglich. Nur Endsteine ergibt Heads and Tails, nur Honours ist ebenfalls Limit.', en: 'No chows: only pungs possible. Only terminals gives Heads and Tails, only honours is a limit too.' }, rarity: 3, standard: true, form: 'terminals_honours' },
  { id: 'dbl_little_three_dragons', category: 'double', rule: 'dbl_little_three_dragons', name: { de: 'Drei kleine Drachen', en: 'Little three dragons' }, text: { de: 'Zwei Drachen-Pungs und das dritte Drachenpaar: 1 Verdopplung zusätzlich zu den zwei Drachen-Verdopplungen.', en: 'Two dragon pungs and the third dragon as pair: 1 double in addition to the two dragon doubles.' }, example: 'rrr ggg 123b 456c ww', tip: { de: 'Der dritte Drachen-Pung macht daraus die Drei großen Drachen (Limit).', en: 'The third dragon pung makes it Big Three Dragons (limit).' }, rarity: 3, standard: true, form: 'dragons' },
  { id: 'dbl_little_four_winds', category: 'double', rule: 'dbl_little_four_winds', name: { de: 'Vier kleine Winde', en: 'Little four winds' }, text: { de: 'Drei Wind-Pungs und das vierte Windpaar: 1 Verdopplung. Vier Wind-Pungs sind ein Limit.', en: 'Three wind pungs and the fourth wind as pair: 1 double. Four wind pungs are a limit.' }, example: 'EEE SSS WWW 123b NN', tip: { de: 'Winde werden früh abgeworfen: rufe sie, sobald du ein Paar hast.', en: 'Winds get discarded early: claim them as soon as you hold a pair.' }, rarity: 4, standard: true, form: 'winds' },
  { id: 'dbl_zero_point_hand', category: 'double', rule: 'dbl_zero_point_hand', name: { de: 'Hühnerhand (Zero Point Hand)', en: 'Chicken hand' }, text: { de: 'Eine Hand ohne jeden Punkt außer Mahjong (nur Chows, wertloses Paar, kein Bonus): 1 Verdopplung als Trost.', en: 'A hand without any point except Mahjong (only chows, worthless pair, no bonus): 1 double as consolation.' }, example: '123b 456c 789k 234k 55b', tip: { de: 'Schnell, aber wenig wert: 20 Punkte × 2. Als Ost trotzdem ein guter Weg, Geber zu bleiben.', en: 'Fast but cheap: 20 points × 2. As East still a good way to stay dealer.' }, rarity: 2, standard: true, form: 'standard' },

  // --- Limit-Hände ---
  { id: 'lim_thirteen_orphans', category: 'limit', rule: 'lim_thirteen_orphans', name: { de: 'Dreizehn Waisen', en: 'Thirteen Orphans' }, text: { de: 'Je eine 1 und 9 jeder Farbe, alle vier Winde, alle drei Drachen, davon ein Stein doppelt. Muss verdeckt bleiben; darf nach Option den vierten Stein eines verdeckten Kongs rauben.', en: 'One 1 and 9 of each suit, all four winds, all three dragons, one of them doubled. Must stay concealed; by option may rob the fourth tile of a concealed kong.' }, example: '19b 19c 19k ESWN rgw E', tip: { de: 'Nur mit 9 oder mehr verschiedenen Waisen zu Beginn versuchen. Alles andere abwerfen, Mittelsteine sind wertlos.', en: 'Only attempt with 9 or more different orphans at the start. Discard everything else; middle tiles are worthless.' }, rarity: 5, standard: true, form: 'thirteen_orphans' },
  { id: 'lim_nine_gates', category: 'limit', rule: 'lim_nine_gates', name: { de: 'Neun Tore', en: 'Nine Gates' }, text: { de: '1112345678999 einer Farbe, verdeckt, plus ein beliebiger weiterer Stein derselben Farbe. Wartet auf neun verschiedene Steine.', en: '1112345678999 of one suit, concealed, plus any further tile of the same suit. Waits on nine different tiles.' }, example: '1112345678999b 5b', tip: { de: 'Entsteht aus einer verdeckten reinen Farbe mit Pungs auf 1 und 9.', en: 'Arises from a concealed full flush with pungs of 1 and 9.' }, rarity: 5, standard: true, form: 'nine_gates' },
  { id: 'lim_heavenly', category: 'limit', rule: 'lim_heavenly', name: { de: 'Himmlische Hand', en: 'Heavenly Hand' }, text: { de: 'Ost gewinnt mit den 14 gegebenen Steinen, bevor ein Abwurf gemacht wurde.', en: 'East wins with the 14 dealt tiles before any discard.' }, example: null, tip: { de: 'Reines Glück.', en: 'Pure luck.' }, rarity: 5, standard: true },
  { id: 'lim_earthly', category: 'limit', rule: 'lim_earthly', name: { de: 'Irdische Hand', en: 'Earthly Hand' }, text: { de: 'Ein Spieler gewinnt mit Osts erstem Abwurf.', en: 'A player wins on East\'s first discard.' }, example: null, tip: { de: 'Reines Glück.', en: 'Pure luck.' }, rarity: 5, standard: true },
  { id: 'lim_four_kongs', category: 'limit', rule: 'lim_four_kongs', name: { de: 'Vier Kongs', en: 'Fourfold Plenty' }, text: { de: 'Vier Kongs (offen oder verdeckt) und ein Paar.', en: 'Four kongs (exposed or concealed) and a pair.' }, example: null, tip: { de: 'Jeder Kong bringt einen Ersatzstein; die Hand wird oft erst mit dem letzten Ersatzstein fertig.', en: 'Each kong brings a replacement tile; the hand often completes only with the last one.' }, rarity: 5, standard: true, form: 'all_pungs' },
  { id: 'lim_all_honours', category: 'limit', rule: 'lim_all_honours', name: { de: 'Nur Honours', en: 'All Honours' }, text: { de: 'Vier Pungs/Kongs aus Winden und Drachen plus ein Honours-Paar.', en: 'Four pungs/kongs of winds and dragons plus an honour pair.' }, example: 'EEE SSS WWW rrr gg', tip: { de: 'Entsteht aus einer Nur-Endsteine-und-Honours-Hand ohne Endsteine.', en: 'Arises from an all-terminals-and-honours hand without terminals.' }, rarity: 5, standard: true, form: 'all_honours' },
  { id: 'lim_big_four_winds', category: 'limit', rule: 'lim_big_four_winds', name: { de: 'Vier große Winde', en: 'Big Four Winds' }, text: { de: 'Pungs oder Kongs aller vier Winde plus beliebiges Paar.', en: 'Pungs or kongs of all four winds plus any pair.' }, example: 'EEE SSS WWW NNN 55c', tip: { de: 'Aus den vier kleinen Winden mit dem vierten Wind-Pung.', en: 'From Little Four Winds with the fourth wind pung.' }, rarity: 5, standard: true, form: 'winds' },
  { id: 'lim_big_three_dragons', category: 'limit', rule: 'lim_big_three_dragons', name: { de: 'Drei große Drachen', en: 'Big Three Dragons' }, text: { de: 'Pungs oder Kongs aller drei Drachen plus ein Satz und ein Paar.', en: 'Pungs or kongs of all three dragons plus a set and a pair.' }, example: 'rrr ggg www 123b 55c', tip: { de: 'Aus den drei kleinen Drachen mit dem dritten Drachen-Pung.', en: 'From Little Three Dragons with the third dragon pung.' }, rarity: 5, standard: true, form: 'dragons' },
  { id: 'lim_hidden_treasure', category: 'limit', rule: 'lim_hidden_treasure', name: { de: 'Verborgener Schatz', en: 'Buried Treasure' }, text: { de: 'Vier verdeckte Pungs (nicht gerufen) plus Paar, Gewinn per Selbstzug.', en: 'Four concealed pungs (not claimed) plus pair, won by self-draw.' }, example: '111b 222b 333b EEE 99b', tip: { de: 'Nicht rufen, auch wenn es verlockt. Drei verdeckte Pungs bringen unterwegs schon eine Verdopplung.', en: 'Do not call, however tempting. Three concealed pungs already bring a double on the way.' }, rarity: 4, standard: true, form: 'all_pungs_concealed' },
  { id: 'lim_concealed_full_flush', category: 'limit', rule: 'lim_concealed_full_flush', name: { de: 'Verdeckte reine Farbe', en: 'Concealed Full Flush' }, text: { de: 'Reine Farbe ohne gerufene Sätze.', en: 'Full flush without claimed sets.' }, example: '123b 456b 789b 234b 99b', tip: { de: 'Die reine Farbe mit 3 Verdopplungen ist die offene Variante; verdeckt zählt sie das Limit.', en: 'The full flush with 3 doubles is the exposed variant; concealed it scores the limit.' }, rarity: 4, standard: true, form: 'full_flush_concealed' },
  { id: 'lim_heads_and_tails', category: 'limit', rule: 'lim_heads_and_tails', name: { de: 'Nur Endsteine (Heads and Tails)', en: 'Heads and Tails' }, text: { de: 'Alle Sätze und das Paar aus 1ern und 9ern.', en: 'All sets and the pair from 1s and 9s.' }, example: '111b 999b 111c 999k 99c', tip: { de: 'Endsteine werden früh abgeworfen: rufe Pungs, sonst wird es zu langsam.', en: 'Terminals get discarded early: claim pungs, otherwise it becomes too slow.' }, rarity: 5, standard: true, form: 'terminals' },
  { id: 'lim_all_green', category: 'limit', rule: 'lim_all_green', name: { de: 'Kaiserliche Jade (All Green)', en: 'Imperial Jade' }, text: { de: 'Nur 2, 3, 4, 6, 8 Bambus und Grüner Drache.', en: 'Only 2, 3, 4, 6, 8 bamboo and green dragon.' }, example: '222b 333b 444b 666b gg', tip: { de: 'Chows 234b sind erlaubt; 5 und 7 Bambus sind tabu.', en: 'Chows 234 bamboo are allowed; 5 and 7 bamboo are taboo.' }, rarity: 5, standard: true, form: 'all_green' },
  { id: 'lim_plum_blossom', category: 'limit', rule: 'lim_plum_blossom', name: { de: 'Pflaumenblüte vom Dach', en: 'Gathering Plum Blossom from the Roof' }, text: { de: 'Gewinn mit 5 Kreise als Ersatzstein nach einem Kong.', en: 'Winning with 5 circles as the replacement tile after a kong.' }, example: null, tip: { de: 'Mit einem Warten auf 5 Kreise lohnt sich jeder Kong.', en: 'With a wait on 5 circles every kong pays.' }, rarity: 5, standard: true },
  { id: 'lim_plucking_moon', category: 'limit', rule: 'lim_plucking_moon', name: { de: 'Mond vom Meeresgrund', en: 'Plucking the Moon from the Sea' }, text: { de: 'Gewinn mit 1 Kreise als letztem Stein der Wand (Selbstzug).', en: 'Winning with 1 circles as the last tile of the wall (self-draw).' }, example: null, tip: { de: 'Selten planbar; ein Warten auf 1 Kreise am Ende der Wand halten.', en: 'Rarely plannable; keep a wait on 1 circles at the end of the wall.' }, rarity: 5, standard: true },
  { id: 'lim_scratching_pole', category: 'limit', rule: 'lim_scratching_pole', name: { de: 'Tragestange kratzen', en: 'Scratching a Carrying Pole' }, text: { de: 'Gewinn durch Raub des Kongs mit 2 Bambus.', en: 'Winning by robbing a kong with 2 bamboo.' }, example: null, tip: { de: 'Nur beim Ergänzungs-Kong eines Gegners möglich.', en: 'Only possible on an opponent\'s extended kong.' }, rarity: 5, standard: true },
  { id: 'lim_twofold_fortune', category: 'limit', rule: 'lim_twofold_fortune', name: { de: 'Doppeltes Glück', en: 'Twofold Fortune' }, text: { de: 'Gewinn mit dem Ersatzstein nach zwei unmittelbar aufeinanderfolgenden Kongs.', en: 'Winning with the replacement tile after two immediately consecutive kongs.' }, example: null, tip: { de: 'Nicht planbar.', en: 'Not plannable.' }, rarity: 5, standard: true },

  // --- Optionen ---
  { id: 'lim_wriggling_snake', category: 'option', rule: 'lim_wriggling_snake', name: { de: 'Sich windende Schlange', en: 'Wriggling Snake' }, text: { de: 'BMJA-Sonderhand (Option): ein Paar 1er und je eine 2 bis 9 derselben Farbe, dazu je ein Stein jedes Windes. Nur verdeckt (der letzte Stein darf gerufen werden). Zählt das Limit.', en: 'BMJA special hand (option): a pair of 1s and one each of 2 to 9 in the same suit, plus one of each wind. Concealed only (the last tile may be claimed). Scores the limit.' }, example: '11b 23456789b ESWN', tip: { de: 'Braucht acht verschiedene Steine einer Farbe und alle vier Winde: nur mit sehr passendem Start versuchen.', en: 'Needs eight different tiles of one suit and all four winds: only try with a very fitting start.' }, rarity: 5, standard: false, form: 'wriggling_snake' },
  { id: 'lim_knitting', category: 'option', rule: 'lim_knitting', name: { de: 'Strickmuster', en: 'Knitting' }, text: { de: 'BMJA-Sonderhand (Option): sieben "gestrickte" Paare, jedes aus derselben Zahl in zwei festen Farben (z. B. 3 Bambus und 3 Kreise), keine Honours, alle Zahlen verschieden. Nur verdeckt. Zählt das Limit.', en: 'BMJA special hand (option): seven "knitted" pairs, each the same number in two fixed suits (e.g. 3 bamboo and 3 circles), no honours, all numbers different. Concealed only. Scores the limit.' }, example: '1234567b 1234567c', tip: { de: 'Wie Sieben Paare, nur über zwei Farben: halte die beiden Farben, wirf die dritte und alle Honours.', en: 'Like Seven Pairs but across two suits: keep the two suits, discard the third and all honours.' }, rarity: 5, standard: false, form: 'knitting' },
  { id: 'lim_triple_knitting', category: 'option', rule: 'lim_triple_knitting', name: { de: 'Dreifaches Strickmuster', en: 'Triple Knitting' }, text: { de: 'BMJA-Sonderhand (Option): vier Drillinge aus derselben Zahl in allen drei Farben plus ein gestricktes Paar aus zwei Farben, alle Zahlen verschieden, keine Honours. Nur verdeckt. Zählt das Limit.', en: 'BMJA special hand (option): four triplets of the same number in all three suits plus a knitted pair from two suits, all numbers different, no honours. Concealed only. Scores the limit.' }, example: '13579b 13579c 1357k', tip: { de: 'Sammle Zahlen quer über die Farben statt Reihen; Einzelsteine sind hier wertvoll.', en: 'Collect numbers across the suits instead of runs; single tiles are valuable here.' }, rarity: 5, standard: false, form: 'triple_knitting' },
  { id: 'lim_all_pair_honours', category: 'option', rule: 'lim_all_pair_honours', name: { de: 'Paare aus Endsteinen und Honours', en: 'All Pair Honours' }, text: { de: 'BMJA-Sonderhand (Option): sieben verschiedene Paare, alle aus 1ern, 9ern, Winden und Drachen. Nur verdeckt. Zählt das Limit.', en: 'BMJA special hand (option): seven different pairs, all from 1s, 9s, winds and dragons. Concealed only. Scores the limit.' }, example: '11b 99b 11c 99k EE SS rr', tip: { de: 'Endsteine und Honours werden früh abgeworfen; Paare davon sind leichter zu sammeln als Pungs.', en: 'Terminals and honours get discarded early; pairs of them are easier to collect than pungs.' }, rarity: 5, standard: false, form: 'all_pair_honours' },
  { id: 'lim_seven_pairs', category: 'option', rule: 'lim_seven_pairs', name: { de: 'Sieben Paare', en: 'Seven Pairs' }, text: { de: 'Sieben verschiedene Paare (Option, nicht bei Millington). In dieser App als Limit gewertet, wenn die Regeloption aktiv ist.', en: 'Seven different pairs (option, not in Millington). Scored as a limit in this app when the rule option is on.' }, example: '11b 22b 33c 44c 55k EE rr', tip: { de: 'Nur mit vier oder mehr Paaren zu Beginn ansteuern; Rufen ist ausgeschlossen.', en: 'Only aim for it with four or more pairs at the start; calling is excluded.' }, rarity: 4, standard: false, form: 'seven_pairs' },
];

export const CATEGORIES = ['basics', 'points', 'double', 'limit', 'option'];

import { SCORE_RULES } from '../scoring/table.js';
import { HK_FANS } from '../scoring/hongkong.js';
import { RIICHI_YAKU } from '../scoring/riichi.js';

const GENERIC = {
  points: { de: 'Grundpunkte laut Millington-Tabelle. Zählt für Gewinner und Verlierer.', en: 'Base points per the Millington table. Counts for winners and losers.' },
  double: { de: 'Verdoppelt den Handwert.', en: 'Doubles the hand value.' },
  limit: { de: 'Limit-Hand: zählt genau das Limit.', en: 'Limit hand: scores exactly the limit.' },
};

// --- Riichi: Grundlagen und Beispiele je Yaku ---
export const RIICHI_BASICS = [
  { id: 'ri_basics_riichi', category: 'basics', name: { de: 'Riichi ansagen', en: 'Declaring riichi' }, text: { de: 'Ist die verdeckte Hand wartend (Tenpai), kannst du beim Abwurf Riichi ansagen: 1000 Punkte kommen als Stäbchen auf den Tisch, die Hand ist ab jetzt festgelegt. Du wirfst nur noch gezogene Steine ab, rufst nichts mehr (ein verdecktes Kan mit dem gezogenen Stein ist erlaubt, wenn das Warten gleich bleibt). Riichi ist ein Yaku (1 Han), Doppel-Riichi beim ersten Abwurf ohne Rufe 2 Han, Ippatsu (Gewinn binnen eines Umlaufs) 1 Han; dazu zählen die Ura-Dora. Bedingungen: mindestens 1000 Punkte, mindestens 4 Steine in der Wand.', en: 'When your concealed hand is ready (tenpai) you may declare riichi with a discard: 1000 points go on the table as a stick and the hand is locked. From then on you discard only drawn tiles and make no calls (a concealed kan with the drawn tile is allowed if the wait stays the same). Riichi is a yaku (1 han), double riichi on the first uninterrupted discard 2 han, ippatsu (winning within one go-around) 1 han; ura dora count too. Requirements: at least 1000 points and at least 4 tiles in the wall.' }, example: null, tip: { de: 'Riichi lohnt fast immer: Es bringt Yaku, Ura-Dora und setzt die Gegner unter Druck. Zögere nur mit einer sehr wertvollen Hand, die auch verdeckt gewinnt (Damaten).', en: 'Riichi almost always pays: it brings a yaku, ura dora and pressures opponents. Hesitate only with a very valuable hand that wins without it (damaten).' }, rarity: 1, standard: true },
  { id: 'ri_basics_yaku', category: 'basics', name: { de: 'Yaku-Pflicht und Rufe', en: 'Yaku requirement and calls' }, text: { de: 'Eine Hand darf nur gewinnen, wenn sie mindestens ein Yaku hat (Dora zählen nicht). Verdeckte Hände haben per Selbstzug immer Menzen Tsumo; per Ron brauchen sie Riichi, Pinfu, Tanyao, Yakuhai oder Ähnliches. Rufe (Chi, Pon, Kan) öffnen die Hand: Menzen-Yaku entfallen, viele Yaku verlieren 1 Han. Wer ruft, braucht einen Plan: Yakuhai-Pung, Tanyao (offen erlaubt: Kuitan), Honitsu, Toitoi.', en: 'A hand may only win with at least one yaku (dora do not count). Concealed hands always have menzen tsumo on self-draw; on ron they need riichi, pinfu, tanyao, yakuhai or similar. Calls (chi, pon, kan) open the hand: closed-only yaku vanish and many yaku lose 1 han. Whoever calls needs a plan: a yakuhai pung, tanyao (open if kuitan), honitsu, toitoi.' }, example: null, tip: { de: 'Der Berater warnt, wenn ein Ruf die Hand yakulos machen würde.', en: 'The advisor warns when a call would leave the hand without a yaku.' }, rarity: 1, standard: true },
  { id: 'ri_basics_furiten', category: 'basics', name: { de: 'Furiten', en: 'Furiten' }, text: { de: 'Liegt einer deiner Wartesteine in deinen eigenen Abwürfen, bist du furiten: kein Ron, nur Selbstzug. Lässt du einen Stein passieren, der deine Hand vervollständigt hätte, bist du bis zum nächsten eigenen Zug furiten; nach Riichi dauerhaft für die Hand.', en: 'If one of your waiting tiles lies among your own discards you are furiten: no ron, only self-draw. If you let a tile pass that would have completed your hand you are furiten until your next turn; after riichi permanently for the hand.' }, example: null, tip: { de: 'Achte beim Umbau der Hand auf früh abgeworfene Nachbarsteine.', en: 'When reshaping the hand, watch out for neighbours you discarded early.' }, rarity: 1, standard: true },
  { id: 'ri_basics_dora', category: 'basics', name: { de: 'Dora, Ura-Dora, rote Fünfer', en: 'Dora, ura dora, red fives' }, text: { de: 'Der aufgedeckte Anzeiger in der toten Wand bestimmt den Dora: die nächsthöhere Zahl (9 → 1), Ost → Süd → West → Nord, Weiß → Grün → Rot. Jeder Dora in der Gewinnhand ist 1 Han, aber kein Yaku. Nach jedem Kan wird ein weiterer Anzeiger aufgedeckt. Mit Riichi zählen zusätzlich die Ura-Dora unter den Anzeigern. Rote Fünfer (eine je Farbe, Option) zählen ebenfalls 1 Han.', en: 'The revealed indicator in the dead wall defines the dora: the next number (9 → 1), East → South → West → North, White → Green → Red. Each dora in the winning hand is 1 han but no yaku. After every kan another indicator is revealed. With riichi the ura dora beneath the indicators count too. Red fives (one per suit, option) also count 1 han.' }, example: null, tip: { de: 'Dora machen billige Hände wertvoll: ein Dora-Paar als Kopf ist Gold wert.', en: 'Dora make cheap hands valuable: a dora pair as the head is worth gold.' }, rarity: 1, standard: true },
  { id: 'ri_basics_scoring', category: 'basics', name: { de: 'Han, Fu und Zahlung', en: 'Han, fu and payment' }, text: { de: 'Grundpunkte = Fu × 2^(Han+2), gedeckelt: Mangan 2000 (ab 5 Han), Haneman 3000, Baiman 4000, Sanbaiman 6000, Yakuman 8000. Ron: der Abwerfende zahlt das Vierfache (Ost als Gewinner das Sechsfache). Tsumo: alle zahlen, Ost doppelt; Ost als Gewinner bekommt von allen doppelt. Beträge werden auf 100 aufgerundet. Honba: 300 je Zähler beim Ron, 100 von jedem beim Tsumo. Alle Riichi-Stäbchen gehen an den Gewinner.', en: 'Base points = fu × 2^(han+2), capped: mangan 2000 (from 5 han), haneman 3000, baiman 4000, sanbaiman 6000, yakuman 8000. Ron: the discarder pays four times (six times when East wins). Tsumo: everyone pays, East double; East as winner collects double from all. Amounts round up to 100. Honba: 300 per counter on ron, 100 from each on tsumo. All riichi sticks go to the winner.' }, example: null, tip: { de: 'Häufige Werte: 1000 (1 Han 30 Fu), 2000, 3900, 8000 (Mangan), 12000 (Haneman-Ron), 32000 (Yakuman).', en: 'Common values: 1000 (1 han 30 fu), 2000, 3900, 8000 (mangan), 12000 (haneman ron), 32000 (yakuman).' }, rarity: 1, standard: true },
  { id: 'ri_basics_draw', category: 'basics', name: { de: 'Unentschieden, Tenpai, Honba', en: 'Exhaustive draw, tenpai, honba' }, text: { de: 'Ist die Wand leer, zeigen wartende Spieler ihre Hand: die Nicht-Wartenden zahlen insgesamt 3000 an die Wartenden (Noten-Bappu). Ost bleibt Geber, wenn Ost wartend war; der Honba-Zähler steigt bei jedem Unentschieden und jedem Ost-Gewinn. Fällt ein Spieler unter 0 Punkte, endet das Spiel (Option). Ein Hanchan besteht aus Ost- und Südrunde.', en: 'When the wall is empty, ready players reveal their hands: the non-ready pay 3000 in total to the ready (noten bappu). East stays dealer if East was ready; the honba counter rises with every draw and every East win. If a player drops below 0 points the game ends (option). A hanchan consists of the East and South rounds.' }, example: null, tip: { de: 'Spät im Spiel zählt Tenpai bares Geld: halte die Hand wartend, auch ohne Yaku.', en: 'Late in the hand tenpai is worth money: keep the hand ready even without a yaku.' }, rarity: 1, standard: true },
];

const RIICHI_EXAMPLES = {
  pinfu: ['234b 567c 678k 345k 88c', 'standard'], tanyao: ['234b 567c 678k 345k 88c', 'standard'], iipeikou: ['123b 123b 456c 789k 55c', 'standard'],
  yakuhai_dragon: ['rrr 123b 456c 789k 55c', 'standard'], yakuhai_seat: ['EEE 123b 456c 789k 55c', 'standard'], yakuhai_round: ['EEE 123b 456c 789k 55c', 'standard'],
  chiitoitsu: ['11b 22b 33c 44c 55k EE rr', 'seven_pairs'], sanshoku: ['123b 123c 123k 456c 55c', 'standard'], ittsu: ['123b 456b 789b 234c 55c', 'standard'],
  chanta: ['123b 789c 999k EEE 11c', 'terminals_honours'], honroutou: ['111b 999c EEE rrr 99k', 'terminals_honours'], toitoi: ['111b 555c 999k EEE rr', 'all_pungs'],
  sanankou: ['111b 222b 333c 456k 55k', 'all_pungs'], sanshoku_doukou: ['222b 222c 222k 456c 55c', 'all_pungs'], shousangen: ['rrr ggg 123b 456c ww', 'dragons'],
  honitsu: ['123b 456b 999b EEE rr', 'half_flush'], junchan: ['123b 789c 999k 111k 11c', 'terminals'], ryanpeikou: ['123b 123b 456c 456c 55c', 'standard'],
  chinitsu: ['123b 456b 789b 234b 99b', 'full_flush'], kokushi: ['19b 19c 19k ESWN rgw E', 'thirteen_orphans'], suuankou: ['111b 222b 333c EEE 55k', 'all_pungs_concealed'],
  daisangen: ['rrr ggg www 123b 55c', 'dragons'], shousuushii: ['EEE SSS WWW 123b NN', 'winds'], daisuushii: ['EEE SSS WWW NNN 55c', 'winds'],
  tsuuiisou: ['EEE SSS WWW rrr gg', 'all_honours'], chinroutou: ['111b 999b 111c 999k 99c', 'terminals'], ryuuiisou: ['222b 333b 444b 666b gg', 'all_green'],
  chuuren: ['1112345678999b 5b', 'nine_gates'],
};

const RIICHI_GENERIC = {
  yaku1: { de: 'Yaku mit 1 Han.', en: 'Yaku worth 1 han.' },
  yaku2: { de: 'Yaku mit mehreren Han (offen oft 1 Han weniger).', en: 'Yaku worth several han (often 1 han less when open).' },
  yakuman: { de: 'Yakuman: zählt 8000 Grundpunkte (32000 bzw. 48000 für Ost); mehrere Yakuman addieren sich.', en: 'Yakuman: 8000 base points (32000, or 48000 for East); several yakuman add up.' },
  dora: { de: 'Zählt je Stein 1 Han, ist aber kein Yaku.', en: 'Counts 1 han per tile but is no yaku.' },
};

function riichiLexicon() {
  const generated = Object.entries(RIICHI_YAKU).filter(([id]) => id !== 'fu').map(([id, y]) => {
    const category = y.yakuman ? 'yakuman' : y.dora ? 'dora' : y.han[0] >= 2 ? 'yaku2' : 'yaku1';
    const ex = RIICHI_EXAMPLES[id];
    const worth = y.yakuman ? { de: 'Yakuman', en: 'Yakuman' } : y.dora ? { de: '1 Han je Stein', en: '1 han per tile' } : { de: `${y.han[0]} Han verdeckt${y.han[1] === null ? ', nur verdeckt' : y.han[1] !== y.han[0] ? `, offen ${y.han[1]}` : ''}`, en: `${y.han[0]} han closed${y.han[1] === null ? ', closed only' : y.han[1] !== y.han[0] ? `, open ${y.han[1]}` : ''}` };
    return {
      id: `ri_${id}`, category, rule: id, variant: 'riichi', name: { de: y.de, en: y.en },
      text: { de: `${RIICHI_GENERIC[category].de} ${worth.de}.`, en: `${RIICHI_GENERIC[category].en} ${worth.en}.` },
      example: ex ? ex[0] : null, tip: null, rarity: y.yakuman ? 5 : category === 'yaku2' ? 3 : 2, standard: true, form: ex ? ex[1] : undefined, generated: true,
    };
  });
  return [...RIICHI_BASICS.map((e) => ({ ...e, variant: 'riichi' })), ...generated];
}

// --- Hong Kong: Grundlagen und Beispiele ---
export const HK_BASICS = [
  { id: 'hk_basics_fan', category: 'basics', name: { de: 'Fan und Mindest-Fan', en: 'Fan and minimum fan' }, text: { de: 'Jede Eigenschaft der Gewinnhand bringt Fan (Punkte). Nur der Gewinner zählt. Eine Hand darf nur gewinnen, wenn sie die Mindest-Fan erreicht (Voreinstellung 3, Option 0 oder 1). Grundwert je Fan: 0 → 1, 1 → 2, 2 → 4, 3 → 8, 4 → 16, 5 → 24, 6 → 32, 7 → 48, 8 → 64, 9 → 96, 10 → 128, 11 → 192, 12 → 256, 13 (Limit) → 384.', en: 'Every property of the winning hand brings fan (points). Only the winner counts. A hand may win only when it reaches the minimum fan (default 3, option 0 or 1). Base value per fan: 0 → 1, 1 → 2, 2 → 4, 3 → 8, 4 → 16, 5 → 24, 6 → 32, 7 → 48, 8 → 64, 9 → 96, 10 → 128, 11 → 192, 12 → 256, 13 (limit) → 384.' }, example: null, tip: { de: 'Mit Mindest-Fan 3 gewinnt eine reine Chow-Hand nicht: plane Drachen-Pungs, eine Farbe oder Nur-Pungs ein.', en: 'With minimum fan 3 a plain chow hand cannot win: plan for dragon pungs, one suit or all pungs.' }, rarity: 1, standard: true },
  { id: 'hk_basics_payment', category: 'basics', name: { de: 'Zahlung', en: 'Payment' }, text: { de: 'Selbstzug: jeder der drei Verlierer zahlt den Grundwert. Gewinn durch Abwurf: nur der Abwerfende zahlt, bei "halber Verantwortung" (半銃) das Doppelte, bei "voller Verantwortung" (全銃) das Dreifache des Grundwerts. Ost hat keine Sonderrolle bei der Zahlung, bleibt aber nach Gewinn und Unentschieden Geber.', en: 'Self-draw: each of the three losers pays the base value. Win by discard: only the discarder pays, double the base value under "half responsibility" (半銃), triple under "full responsibility" (全銃). East has no special payment role but stays dealer after a win or draw.' }, example: null, tip: { de: 'Abwürfe in eine offene Farbenhand sind teuer: du zahlst allein.', en: 'Discarding into an exposed flush hand is expensive: you pay alone.' }, rarity: 1, standard: true },
  { id: 'hk_basics_flowers', category: 'basics', name: { de: 'Blumen und Jahreszeiten', en: 'Flowers and seasons' }, text: { de: 'Blumen und Jahreszeiten werden sofort ausgelegt und ersetzt. Die eigene Blume und die eigene Jahreszeit (Nummer des Sitzwindes) bringen je 1 Fan, alle vier Blumen oder alle vier Jahreszeiten 2 Fan, gar kein Bonusstein 1 Fan.', en: 'Flowers and seasons are laid out immediately and replaced. Your own flower and own season (seat wind number) bring 1 fan each, all four flowers or all four seasons 2 fan, no bonus tile at all 1 fan.' }, example: null, tip: { de: 'Bonussteine sind reines Glück; die Fan aus der Hand entscheiden.', en: 'Bonus tiles are pure luck; the fan from the hand decide.' }, rarity: 1, standard: true },
];

const HK_EXAMPLES = {
  hk_all_chows: ['123b 456c 789k 234k 55b', 'standard'], hk_all_pungs: ['111b 555c 999k EEE rr', 'all_pungs'], hk_half_flush: ['123b 456b 999b EEE rr', 'half_flush'],
  hk_full_flush: ['123b 456b 789b 234b 99b', 'full_flush'], hk_dragon_pung: ['rrr 123b 456c 789k 55c', 'standard'], hk_seat_wind: ['EEE 123b 456c 789k 55c', 'standard'],
  hk_prevailing_wind: ['EEE 123b 456c 789k 55c', 'standard'], hk_little_three_dragons: ['rrr ggg 123b 456c ww', 'dragons'], hk_big_three_dragons: ['rrr ggg www 123b 55c', 'dragons'],
  hk_little_four_winds: ['EEE SSS WWW 123b NN', 'winds'], hk_big_four_winds: ['EEE SSS WWW NNN 55c', 'winds'], hk_all_honours: ['EEE SSS WWW rrr gg', 'all_honours'],
  hk_all_terminals: ['111b 999b 111c 999k 99c', 'terminals'], hk_mixed_terminals: ['111b 999c EEE rrr 99k', 'terminals_honours'], hk_four_concealed_pungs: ['111b 222b 333b EEE 99b', 'all_pungs_concealed'],
  hk_thirteen_orphans: ['19b 19c 19k ESWN rgw E', 'thirteen_orphans'], hk_nine_gates: ['1112345678999b 5b', 'nine_gates'], hk_seven_pairs: ['11b 22b 33c 44c 55k EE rr', 'seven_pairs'],
};

function hkLexicon() {
  const generated = Object.entries(HK_FANS).map(([id, f]) => {
    const category = f.value >= 10 ? 'limit' : f.value >= 3 ? 'fan3' : 'fan1';
    const ex = HK_EXAMPLES[id];
    return {
      id: `lex_${id}`, category, rule: id, variant: 'hongkong', name: { de: f.de, en: f.en },
      text: { de: `${f.value} Fan.${f.value >= 13 ? ' Limit-Hand.' : ''}`, en: `${f.value} fan.${f.value >= 13 ? ' Limit hand.' : ''}` },
      example: ex ? ex[0] : null, tip: null, rarity: f.value >= 10 ? 5 : f.value >= 3 ? 3 : 1, standard: id !== 'hk_seven_pairs', form: ex ? ex[1] : undefined, generated: true,
    };
  });
  return [...HK_BASICS.map((e) => ({ ...e, variant: 'hongkong' })), ...generated];
}

export const CATEGORIES_BY_VARIANT = {
  classical: CATEGORIES,
  riichi: ['basics', 'yaku1', 'yaku2', 'yakuman', 'dora'],
  hongkong: ['basics', 'fan1', 'fan3', 'limit'],
};

export function categoriesFor(variant = 'classical') {
  return CATEGORIES_BY_VARIANT[variant] ?? CATEGORIES;
}

/** Lexikon plus automatisch erzeugte Einträge für alle Scoring-Zeilen ohne eigenen Eintrag. */
export function fullLexicon(variant = 'classical') {
  if (variant === 'riichi') return riichiLexicon();
  if (variant === 'hongkong') return hkLexicon();
  const covered = new Set(LEXICON.map((e) => e.rule).filter(Boolean));
  const generated = Object.entries(SCORE_RULES)
    .filter(([id]) => !covered.has(id) && id !== 'mahjong')
    .map(([id, r]) => ({
      id: `rule_${id}`,
      category: r.kind === 'limit' ? 'limit' : r.kind === 'double' ? 'double' : 'points',
      rule: id,
      name: { de: r.de, en: r.en },
      text: GENERIC[r.kind],
      example: null,
      tip: null,
      rarity: r.kind === 'limit' ? 5 : r.scope === 'winner' ? 2 : 1,
      standard: true,
      generated: true,
    }));
  return [...LEXICON.map((e) => ({ ...e, variant: 'classical' })), ...generated.map((e) => ({ ...e, variant: 'classical' }))];
}

export const VARIANTS = ['classical', 'hongkong', 'riichi'];

export function lexiconById(id) {
  for (const v of VARIANTS) {
    const e = fullLexicon(v).find((x) => x.id === id);
    if (e) return e;
  }
  return null;
}

export function lexiconByRule(ruleId) {
  return LEXICON.find((e) => e.rule === ruleId) ?? null;
}
